dist: focal
language: node_js
node_js:
  - 20
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache    
before_install:
  - npm install -g npm@10.2.4
script:
  - npm run test:ci
  - npm run test:cypress:ci
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  repo: rospiel/react-clean-architecture-publish
  target_branch: main
  on:
    branch: main
notifications:
  email: false    